### ISSUE TITLE
Accountname memory

### ISSUE THREAD

**Issue by Frostimultibox** [WowOpenBox/WowOpenBox#104]
I'm using 5 different accounts with 5 differents emails.
When I launch my characters, if the connection drop off (disconnection), there is the same email account on all wow instance (sometimes the first account, sometimes the last account typed).

Not very a problem, just saying.

**Comment by mooreatv** [comment]
Thanks for taking the time to file an issue

You need to edit and use `launchwow.bat`  so it virtualizes your config.wtf so the email is saved?

Please confirm that fixes it and/or how you launch you wow

**Comment by mooreatv** [comment]
will close this as I think it's solved by the bat file. lmk if not
