### ISSUE TITLE
Closed WOB, Accidently closed WOB1, reopen WOB, tried to Swap WOB2, error.

### ISSUE THREAD

**Issue by I3igAl** [WowOpenBox/WowOpenBox#107]
Sorry for shit explanation Moorea, its 3am. I accidently closed WOB and then WOB1 while using Alt Tab to try and close other windows. when I reopened WOB and then tried to swap windows, these two errors popped up:

![image](https://user-images.githubusercontent.com/80173503/112615221-711ecf00-8ddf-11eb-8584-e28258288dd1.png)

![image](https://user-images.githubusercontent.com/80173503/112615238-7714b000-8ddf-11eb-8836-c3ab6c77713c.png)
After I recaptured a fresh WOB1 it was no longer a problem

**Comment by mooreatv** [comment]
Thanks for the report!

**Comment by mooreatv** [comment]
fixed it in my current change (which is a bit big and not finished so not released yet)

it will not swap until you have a WOB1, I hope that's ok (ie you would need to "forget" + recapture instead of swap)

**Comment by mooreatv** [comment]
fixed in 4.1.9
