### ISSUE TITLE
"can't capture foreground  window it's (already) ours" unable to capture window problem

### ISSUE THREAD

**Issue by makketz** [WowOpenBox/WowOpenBox#112]
trying to capture my first window and i get the error in the subject

**Comment by mooreatv** [comment]
@makketz thanks for taking the time to file an issue, but can you say a bit more:

which game or window you're trying to capture?

how are you trying to capture it?

with the error above it seems you try to use the "capture foreground window" but didn't use the hotkey (`Ctrl-Shift-C` after making sure the game/window you want to capture is in the foreground?)

**Comment by mooreatv** [comment]
fixed (by making the UI more clear) in 4.2.3

**Comment by mooreatv** [comment]
next time just reopen if you continue to encounter issues
