### ISSUE TITLE
more explination on"can't capture foreground window it's (already) ours" unable to capture window problem

### ISSUE THREAD

**Issue by makketz** [WowOpenBox/WowOpenBox#115]
im playing WoW trying to capture it as the main screen 1 that I have the layout set up for. When I click capture or use shift+ctrl+c i get the error. funny enough tho if I keep clicking or ctrl+shift+c the error window gets captured. so i have the game open, open box is running along with my game im trying to capture. and i get this error  "can't capture foreground window it's (already) ours" and now another saying "no application error window found" when trying to caputre it. thats about the extent of my situation. If u have a solution or anything i can attempt thank you kindly.

**Comment by mooreatv** [comment]
First WOB will automatically capture by default; so you don't have to do anything

Just make sure "World of Warcraft" is selected in the Game menu and that "Capture using foreground windows" is unchecked and disabled in the main UI (also make sure you run 4.2.3 or newer)

Then in the Options menu, make sure "Auto Capture Game windows" is checked

It may be useful you reset your settings as you probably have wrong games in the Game menu

Please confirm this solves it

**Comment by mooreatv** [comment]
going to close this as it should be solved by now; please reopen if not

(attach your settings if you reopen)
