### ISSUE TITLE
Profile settings changed after change to another profile

### ISSUE THREAD

**Issue by Muricas** [WowOpenBox/WowOpenBox#119]
**Describe the bug**
I have two profiles:
- "WQHD" with 6 stacked windows of equal dimensions and locations
- "8 windows" with 8 tiled windows of equal size but tiled

I added an additional window to the "8 windows" profile such that it has 9 tiled windows (3 rows of 3). I made sure to save it.

When I switched from "8 windows" to "WQHD", WOB 2's location and dimensions were changed to the settings from "8 windows".

**To Reproduce**
1. Start WOB
2. Create a profile with 6 stacked windows of equal dimensions.
3. Save.
4. Create another profile with 9 tiled windows.
5. Save
6. Switch to the profile with the 6 stacked windows
7. WOB 2 will have incorrect dimensions

**Expected behavior**
Profiles should not be changed by other profiles.

**Screenshots**
![image](https://user-images.githubusercontent.com/81184564/113015680-66e43400-9143-11eb-972e-ef888f2ef366.png)

I use git to check in changes to my settings. This diff shows the changes to the "WQHD" profile before and after adding a 9th window to the "8 windows" profile.

**Round Robin:**
No

**Game:**
World of Warcraft Classic

**Settings:**
[profile-tcls.zip](https://github.com/WowOpenBox/WowOpenBox/files/6230189/profile-tcls.zip)

**Error details:**
N/A

**Additional context**
N/A

**Comment by mooreatv** [comment]
hey so I haven't found a bug per se but I made big improvements to profile handling; can you try again in v4.1.7
(one issue was the window layout UI would not refresh with what is in the profile; which I guess was your issue as if you save after you get the old settings)

**Comment by mooreatv** [comment]
lmk if it happens again with the latest!
