### ISSUE TITLE
Sanity Check for 2nd Rotation Skips is too Agressive

### ISSUE THREAD

**Issue by vahlic** [WowOpenBox/WowOpenBox#125]
**Describe the bug**
When trying to skip all windows but Main you are presented with the following error: Invalid Custom Rotation.  All windows are disabled!

**To Reproduce**
1. Start WOB
2. Start X Wow windows
3. Select to Skip all WOBs except Main
4. Save Configuration
5. From WoW instance press the key assigned to 2nd Rotation Key to produce the error

**Expected behavior**
We should be able to skip all WOB's except main to create a reset to main if partially through a RR cycle.

**Screenshots**
Skip Configuration Example:
![image](https://user-images.githubusercontent.com/81781303/113361195-03a7fc80-9311-11eb-929b-b465399351b7.png)

Error Message:
![image](https://user-images.githubusercontent.com/81781303/113361219-10c4eb80-9311-11eb-9c75-924859f25855.png)

**Round Robin:**
Are you using the _RR exe?  Yes

**Game:**
Which Game are you playing? (Classic? Shadowlands?...)  Classic WoW

**Settings:**
[wowopenboxSettingsWLLMP.txt](https://github.com/WowOpenBox/WowOpenBox/files/6246804/wowopenboxSettingsWLLMP.txt)

**Comment by mooreatv** [comment]
best bug report ever so far!
