### ISSUE TITLE
Add an "Auto Layout" checkbox to the window layout GUI

### ISSUE THREAD

**Issue by RafipiTTV** [WowOpenBox/WowOpenBox#127]
Currently, if any of the options are changed in the window layout GUI, WOB will auto arrange the windows based on those options. But sometimes I want to create a custom layout by dragging windows around myself, and it would be useful to be able to change the options without losing all the custom changes I made.

My solution would be to have another checkbox which if unchecked would allow me to do the above.

An issue that would arise from implementing this would come from increasing the number of windows. Any new window that was added would have to have a default size and position, so that would have to be considered when implementing this idea. And the new window would need to appear on top of other windows so it is not hidden. 

As for the default size and position, I would suggest a position of (0, 0), and the size would be the same as the last window currently being edited in the window layout GUI.

**Comment by mooreatv** [comment]
> As for the default size and position, I would suggest a position of (0, 0), and the size would be the same as the last window currently being edited in the window layout GUI.

note that's already the behavior if you capture more windows past the configured number

dup of #89, usually I keep the older one and close newer issue but there is more context here so will close my older issue instead
