### ISSUE TITLE
additional separate rotations 

### ISSUE THREAD

**Issue by Neokub** [WowOpenBox/WowOpenBox#128]
there is no way to use the skills of a certain wow window 
I would like to add more rotations so that the rotation for a specific game window can be done 

you can add 2nd 3rd 4th 5th rotation, or you can make it so that users can add rotation data themselves, depending on their needs

**Comment by mooreatv** [comment]
fixed in 4.6.0
(at least fixed so you can get 1 key per direct window in addition to the focus hotkey and the 2 RR rotations)
