### ISSUE TITLE
Moving cursor out of games windows and back incorrectly turns on focus follows mouse with RR enabled.

### ISSUE THREAD

**Issue by RafipiTTV** [WowOpenBox/WowOpenBox#133]
Description in title.

Steps to reproduce the behaviour:
With WOB and any number of WoW windows open..
1. Have "Pause when mouse is outside windows" checked in the options menu (bug does not happen with it unchecked)
2. Have focus follows mouse turned on (bug does not happen if it is turned off to start with)
3. Turn on round robin. Focus follows mouse gets turned off automatically.
4. Move cursor away from game windows and back.
5. Focus follows mouse incorrectly gets turned back on while round robin is still turned on.

Expected behaviour would be that focus follows mouse should still be turned off when the cursor is returned to game windows.

Error can be reproduced without logging in to game windows.

**Comment by mooreatv** [comment]
nice bug report! fixed (wasn't that trivial because of the "memory" of mouse focus on when rr goes off)
