### ISSUE TITLE
Ctrl+Shift+T doesn't disable Always on Top

### ISSUE THREAD

**Issue by Xistt** [WowOpenBox/WowOpenBox#135]
I used OMB last night, put my computer to sleep, and at some point the mouse fell, which seemed to be why my computer was awake, so I got on just to put it to sleep.  OMB had put my 2 WoW windows on the left half of my screen, leaving the right for windows like this, but when I got back on my computer WoW was on the right side and I couldn't use my browser or OMB. 
 Ctrl+Shift+T didn't do anything and when I clicked on it on the start bar, WoW hid it before I could click on Always on Top.

0. I closed WOB and WoW
1. I started WOB
2. I started the 2 WoW windows that I had before.  WOB automatically put them on the left half of my screen, leaving the right half for stuff like this window.
2.1 I left Always on Top checked like some kind of forgetful person.
3. I put my computer to sleep and woke it up again.
4. The lower WoW window is where it is supposed to be, but the upper one is on the right half of the screen, on top of this window.  I was still able to pull up OMB, but Ctrl+Shift+T didn't uncheck Always on Top.
5. When I clicked on the upper WoW window to take a screenshot, it stayed on top even though Always on Top was unchecked.  I opened Paint to save the screenshot and WoW stayed on top (even though Always on Top was unchecked).

**Expected behavior**
I expected both WoW windows to stay on the left, the check for Always on Top to disappear when I hit Ctrl+Shift+T, and for WoW to stop staying on top when I deselect Always on Top.

**Screenshots**
I attached one.  I play in 4k.

_Important_:
Rendering?  Don't think so!

**Round Robin:**
Yes!  Thanks for asking! :)

**Game:**
Shadowlands.  Play Shadowlands they said.  It will be fun they said.

I don't think the graphics settings are relevant.

**Settings:**
Drag you wowopenboxSettings.tcl file here to attach it
I tried and it says "We don't support that file type.  Try again with a GIF, JPEG, JPG, MOV, MP4, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX, or ZIP."
However, this is a dump:

array set settings {
	1,posXY	{0 0}
	1,size	{1920 1060}
	1,stayOnTop	0
	2,posXY	{0 1060}
	2,size	{1920 1060}
	2,stayOnTop	0
	3,posXY	{1920 0}
	3,size	{1920 1060}
	3,stayOnTop	0
	4,posXY	{1920 1060}
	4,size	{1920 1060}
	4,stayOnTop	1
	5,posXY	{4 3}
	5,size	{1280 1060}
	5,stayOnTop	1
	6,posXY	{2560 1412}
	6,size	{1280 706}
	6,stayOnTop	1
	7,posXY	{2560 0}
	7,size	{1280 706}
	7,stayOnTop	1
	8,posXY	{2560 706}
	8,size	{1280 706}
	8,stayOnTop	1
	9,posXY	{2560 1412}
	9,size	{1280 706}
	9,stayOnTop	1
	DEBUG	0
	aspectRatio	Any
	autoCapture	1
	autoKillName	WowVoiceProxy.exe
	autoKillOn	1
	autoResetFocusToMain	1
	avoidTaskbar	1
	borderless	1
	captureForegroundWindow	0
	clipboardAtStart	0
	dontCaptureList	explorer.exe
	focusAlsoFG	1
	game	{World of Warcraft}
	games	{"World of Warcraft" "EVE" "Star Wars\u2122: The Old Republic\u2122"}
	hk,capture	Ctrl-Shift-C
	hk,focusFollowMouse	Ctrl-Shift-F
	hk,focusMain	Ctrl-Shift-W
	hk,focusNextWindow	Ctrl-Shift-N
	hk,focusPreviousWindow	Ctrl-Shift-P
	hk,mouseTrack	Ctrl-Shift-M
	hk,overlayToggle	Ctrl-Shift-O
	hk,resetAll	Ctrl-Shift-Alt-R
	hk,rrToggle	Ctrl-Shift-R
	hk,stayOnTopToggle	Ctrl-Shift-T
	hk,swapNextWindow	Ctrl-0xC0
	hk,swapPreviousWindow	Ctrl-Shift-0xC0
	hk1,focus	Ctrl-F1
	hk1,swap	Ctrl-Shift-F1
	hk10,focus	Ctrl-F10
	hk10,swap	Ctrl-Shift-F10
	hk2,focus	Ctrl-F2
	hk2,swap	Ctrl-Shift-F2
	hk3,focus	Ctrl-F3
	hk3,swap	Ctrl-Shift-F3
	hk4,focus	Ctrl-F4
	hk4,swap	Ctrl-Shift-F4
	hk5,focus	Ctrl-F5
	hk5,swap	Ctrl-Shift-F5
	hk6,focus	Ctrl-F6
	hk6,swap	Ctrl-Shift-F6
	hk7,focus	Ctrl-F7
	hk7,swap	Ctrl-Shift-F7
	hk8,focus	Ctrl-F8
	hk8,swap	Ctrl-Shift-F8
	hk9,focus	Ctrl-F9
	hk9,swap	Ctrl-Shift-F9
	ignoreMonitorIdx	0
	lastUpdateChecked	1617603338
	layoutAuto	1
	layoutMaxWindows	32
	layoutOneRowCol	0
	layoutOneSize	1
	layoutScale	1/3
	layoutSnap	1
	layoutStacked	0
	layoutTop	0
	mfIndicator,label	🐭
	mouseDelay	0
	mouseFocusOffAtExit	1
	mouseFocusOnAtStart	0
	mouseInsideGameWindowFocuses	1
	mouseOutsideWindowsPauses	1
	mouseWatchInterval	50
	numWindows	4
	overlayAlpha	0.7
	overlayAnchor	n
	overlayClickable	1
	overlayFocusColor	{#ff0080}
	overlayShowBorder	1
	profile	Default
	profiles	{"Default"}
	rrCustomExcludeList	0
	rrCustomOnKeyUp	1
	rrIndicator,label	⟳
	rrIndicator,x	0.5
	rrIndicator,y	0.7
	rrInterval	5
	rrKeyListAll	{SPACE 1 2 3 4 5 6 7 8 9 0 - = `}
	rrKeyListCustom	{. [ ] F11}
	rrModExcludeList	{RCONTROL RSHIFT}
	showOverlay	1
	swapAlsoFocus	1
}

**Error details:**
No error message.

If the message isn't in English please translate to english
N/A

**Additional context**
It looks like I need to close OMB and WoW each time that I log out.

**Comment by mooreatv** [comment]
First, thanks for the detailed report

While it's not a permanent solution for bugs but know there is a "Reset All" hotkey (default `Ctrl-Shift-Alt-R` which I use after my computer goes to sleep to make sure the windows go back to their assigned positions)

The hotkey for stay on top applies to the window that _wob_ thinks has the focus; so you want to remove stay on top from window4, first do `ctrl-F4` to focus it; then `ctrl-shift-T` 

Or probably simpler:
first click in the main wob window on the WOB you want to change (eg WOB 4) and then you should see the stay on top checkbox, click it and then click "Update"


> It looks like I need to close OMB and WoW each time that I log out.

what do you mean? I guess there is no harm in exiting OMB at any time (as it'll resume where you left off when you start it again later) but... your game windows consume resources if you're not playing - if you're done for the day you can use "Close All and Exit" in the file menu to stop both your games and WOB

**Comment by mooreatv** [comment]
reopen if you still having issue/can reproduce something odd

**Comment by Xistt** [comment]
I haven't tested if it still stays on top, I just loaded WOB, WoW, put it to sleep, and woke it up twice.  The first time I woke it up everything was perfect, but the second time WoW was in the middle of the screen, and I think that is a WoW problem.  It has done that ever since I went 4k.  I was able to move the windows back to top-left and bottom-right with Reset All and Windows Layout, but now the title bar shows up.

Were you ever familiar with Octopus?  I used that way back in the day and one of the things that I liked is that it removed the title bar.  I am still leaning towards using Close All and Exit each time that I put my computer to sleep.

I generally keep programs running that I use every day.  The only time I notice a problem is if I haven't restarted in a while.

Restarting WOB and WoW seems faster than messing with Reset All and Windows Layout.  As a bonus, I wouldn't have the title bar!  However, for the record:

**Describe the bug**
The title bar appears after I put my computer to sleep and wake it up again.

**To Reproduce**
Steps to reproduce the behavior:
1. Start WOB
2. Start 2 Wow windows
3. Put my computer to sleep and wake it up twice.

**Expected behavior**
I expected the title bar to stay hidden [and for my windows to stay put even though I put my computer to sleep]

**Screenshots**
![OMB error 002](https://user-images.githubusercontent.com/81987200/113824064-2fbde600-9734-11eb-9a5a-4a2e5bb9aa2d.png)

_Important_:
No rendering.

**Round Robin:**
Yes! Thanks for asking! :)

Game:
Shadowlands.

I don't think the graphics settings are relevant.

**Settings:**

- [ ] array set settings {
	1,posXY	{0 0}
	1,size	{1920 1060}
	1,stayOnTop	0
	2,posXY	{1920 0}
	2,size	{1920 1060}
	2,stayOnTop	0
	3,posXY	{0 1056}
	3,size	{1920 1060}
	3,stayOnTop	0
	4,posXY	{1920 1060}
	4,size	{1920 1060}
	4,stayOnTop	1
	5,posXY	{4 3}
	5,size	{1280 1060}
	5,stayOnTop	1
	6,posXY	{2560 1412}
	6,size	{1280 706}
	6,stayOnTop	1
	7,posXY	{2560 0}
	7,size	{1280 706}
	7,stayOnTop	1
	8,posXY	{2560 706}
	8,size	{1280 706}
	8,stayOnTop	1
	9,posXY	{2560 1412}
	9,size	{1280 706}
	9,stayOnTop	1
	DEBUG	0
	aspectRatio	Any
	autoCapture	1
	autoKillName	WowVoiceProxy.exe
	autoKillOn	1
	autoResetFocusToMain	1
	avoidTaskbar	1
	borderless	1
	captureForegroundWindow	0
	clipboardAtStart	0
	dontCaptureList	explorer.exe
	focusAlsoFG	1
	game	{World of Warcraft}
	games	{"World of Warcraft" "EVE" "Star Wars\u2122: The Old Republic\u2122"}
	hk,capture	Ctrl-Shift-C
	hk,focusFollowMouse	Ctrl-Shift-F
	hk,focusMain	Ctrl-Shift-W
	hk,focusNextWindow	Ctrl-Shift-N
	hk,focusPreviousWindow	Ctrl-Shift-P
	hk,mouseTrack	Ctrl-Shift-M
	hk,overlayToggle	Ctrl-Shift-O
	hk,resetAll	Ctrl-Shift-Alt-R
	hk,rrToggle	Ctrl-Shift-R
	hk,stayOnTopToggle	Ctrl-Shift-T
	hk,swapNextWindow	Ctrl-0xC0
	hk,swapPreviousWindow	Ctrl-Shift-0xC0
	hk1,focus	Ctrl-F1
	hk1,swap	Ctrl-Shift-F1
	hk10,focus	Ctrl-F10
	hk10,swap	Ctrl-Shift-F10
	hk2,focus	Ctrl-F2
	hk2,swap	Ctrl-Shift-F2
	hk3,focus	Ctrl-F3
	hk3,swap	Ctrl-Shift-F3
	hk4,focus	Ctrl-F4
	hk4,swap	Ctrl-Shift-F4
	hk5,focus	Ctrl-F5
	hk5,swap	Ctrl-Shift-F5
	hk6,focus	Ctrl-F6
	hk6,swap	Ctrl-Shift-F6
	hk7,focus	Ctrl-F7
	hk7,swap	Ctrl-Shift-F7
	hk8,focus	Ctrl-F8
	hk8,swap	Ctrl-Shift-F8
	hk9,focus	Ctrl-F9
	hk9,swap	Ctrl-Shift-F9
	ignoreMonitorIdx	0
	lastUpdateChecked	1617776773
	layoutAuto	0
	layoutMaxWindows	32
	layoutOneRowCol	0
	layoutOneSize	1
	layoutScale	1/3
	layoutSnap	8
	layoutStacked	0
	layoutTop	0
	mainWindowGeometry	225x616+2552+1449
	mfIndicator,label	🐭
	mouseDelay	0
	mouseFocusOffAtExit	1
	mouseFocusOnAtStart	0
	mouseInsideGameWindowFocuses	1
	mouseOutsideWindowsPauses	1
	mouseWatchInterval	50
	numWindows	4
	overlayAlpha	0.7
	overlayAnchor	n
	overlayClickable	1
	overlayFocusColor	{#ff0080}
	overlayShowBorder	1
	profile	Default
	profiles	{"Default"}
	rrCustomExcludeList	0
	rrCustomOnKeyUp	1
	rrIndicator,label	⟳
	rrIndicator,x	0.5
	rrIndicator,y	0.7
	rrInterval	5
	rrKeyListAll	{SPACE 1 2 3 4 5 6 7 8 9 0 - = `}
	rrKeyListCustom	{. [ ] F11}
	rrModExcludeList	{RCONTROL RSHIFT}
	showOverlay	1
	swapAlsoFocus	1
}

**Error details:**
No error message.

If the message isn't in English please translate to english
N/A

Additional context
May the eternal sun shine upon thee

**Comment by mooreatv** [comment]
> Restarting WOB and WoW seems faster than messing with Reset All and Windows Layout.

well it shouldnt be, it's odd the title bar come back; what I can do probably is retry to make borderless on reset all

**Comment by mooreatv** [comment]
I have seen the window border come back too, when changing resolution in game

**Comment by mooreatv** [comment]
I did make a recent fix for this, so closing this for now
