### ISSUE TITLE
Show overlay and focus follow mouse settings change when focus changes

### ISSUE THREAD

**Issue by mvkx** [WowOpenBox/WowOpenBox#139]
Show overlay and focus follow mouse setting checkboxes have odd behavior when mouse cursor/focus changes from WOB to WoW client. Overlay always on (not sure if because of this behavior), even if the setting is changed in TCL file.

![qwd778f](https://user-images.githubusercontent.com/43672315/114540837-adb34d00-9c5e-11eb-9440-696694d52a7b.gif)

**Comment by mooreatv** [comment]
that’s the auto pause that restores the normal settings when not in game windows (you can turn it off in the Options menu)

**Comment by mooreatv** [comment]
will close assuming you see it's a feature on purpose and not a bug, reopen if you think something is off
