### ISSUE TITLE
Global keybinds with profile override

### ISSUE THREAD

**Issue by Muricas** [WowOpenBox/WowOpenBox#140]
**Is your feature request related to a problem? Please describe.**
I use several different profiles for various team setups in WoW Classic. I recently modified the keybinds in one profile. I typically use only a small set of keybinds with OMB, so I removed keybinds for those actions I do not use. Many of the default keybinds interfere with operations in other applications so removal was necessary.

Switching profiles results in the keybinds being loaded for that profile. In order for me to remove the unused keybinds, I will have to modify each of my 10+ profiles.

**Is your feature request specific to a specific Game, if so which one**
N/A

**Describe the solution you'd like**
Adding support for global keybinds that are overridden by profiles would resolve this issue. By default a profile would have no keybinds but instead defer to a global set, but if ones were added to the profile they would override the global keybinds. And any changes to the global keybinds would affect any profile that does not have keybind settings.

**Describe alternatives you've considered**
My alternative is to manually managed the keybinds in the various profiles. This is not out of the ordinary for multiboxing; I regularly use diffing tools to sync saved variables between my characters.

**Additional context**
N/A

**Comment by mooreatv** [comment]
try 4.5.4 and tell me if that doesn't work for you - as in you do make most of your changes in default profile; then save in different profiles (new profile) what you want to be different. it should switch sets fine now

**Comment by mooreatv** [comment]
@Muricas I will close this for now (as 'done') but if you feel some improvements are still needed from 4.5.9 please reopen
