### ISSUE TITLE
Round Robin stopped working

### ISSUE THREAD

**Issue by Wowopenuser** [WowOpenBox/WowOpenBox#146]
I was using WOW open box when all of a sudden Round Robin stopped working. when I press a key that normally round robins it will not anymore. I have Round Robin feature enabled yes. I shut everything down, rebooted it, even installed the latest version but Round Robin still will not work and I have been using it for many months now. 

**Round Robin:**
Are you using the _RR exe?  Yes I am

**Game:**
WOW Classic TBC

**Comment by mooreatv** [comment]
You must have something else somehow changed/interfering? no one else has reported any problem, curious to know what it is though to add to the FAQ?

**Comment by mooreatv** [comment]
going to close this for lack of information on how to reproduce (and nobody else mentioning any problem - go on discord if it happens again)
