### ISSUE TITLE
swapping windows bugging out..

### ISSUE THREAD

**Issue by kraemder** [WowOpenBox/WowOpenBox#149]
I am 2 boxing on classic wow TBC.  I have two monitors.  I'm using the "Press a hotkey to bring window N to the main (1) window" to swap the toons and when I swap, sometimes I can't cast spells or anything - it's still moving the old toon/window instead of the one I swapped to.

*edit*

A little more testing and I see that if I swap windows and then wait a second before typing then it works fine.  If I press a key too quickly then it bugs.

**Comment by mooreatv** [comment]
how quickly? check the tips in the faq to get fast window swapping? if you see in my videos it's nearly instant and I don't have to pause before using spells

**Comment by mooreatv** [comment]
going to close this for lack of info/reproducibility

if still an issue please reopen with details
