### ISSUE TITLE
Update Handles Error

### ISSUE THREAD

**Issue by Yoshana121** [WowOpenBox/WowOpenBox#153]
Loading from one profile to another

**Round Robin:**
Are you using the _RR exe? 
No

**Game:**
Which Game are you playing? (Classic? Shadowlands?...)
TBC

**Error details:**
If you got an application error with details, please copy paste it here 
(or screen shot if can't copy)

![Update Error](https://user-images.githubusercontent.com/111165276/184466192-3310012d-5735-4728-a038-fa46fe011009.png)

**Additional context**
Switching from 10box to new 15 box profile

**Comment by mooreatv** [comment]
does this happen more than once? if so can you try to get minimal steps to get to the error/reproduce it?

**Comment by Yoshana121** [comment]
Only happened the once, and I posted it as that was what the message asked
me to.  I will try and replicate what I was doing when I got the error.

Thanks
CJ

[image: width=]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mooreatv** [comment]
I'll assume it's been fine since, closing
