### ISSUE TITLE
2nd and 3rd widows are not being captured

### ISSUE THREAD

**Issue by Rysteranch** [WowOpenBox/WowOpenBox#160]
**To Reproduce**
1. Start WOB
2. Start 3 Wow windows
3. The first window is captured.  The 2nd and 3rd windows are not placed in their respective screens.  When I mouse over the system tray,  the program has launched,  but shows just a white screen for both wob2 and wob3.
This just started with the pre-patch.
5. See error

**Expected behavior**

**Screenshots**

_Important_:
If your issue is about rendering problems; you must include an example and a screen shot of both your Game main graphic settinsg and advanced Graphic settings

**Round Robin:**
Are you using the _RR exe? yes

**Game:**
Which Game are you playing? war within prepatch

Attach graphic and advanced graphic settings screenshots if relevant

**Settings:**
Drag you wowopenboxSettings.tcl file here to attach it

**Error details:**
If you got an application error with details, please copy paste it here 
(or screen shot if can't copy)

If the message isn't in English please translate to english

**Additional context**

**Comment by Rysteranch** [comment]
And,  now it's working.

**Comment by Larienth** [comment]
@Rysteranch how did you get it to start working? I am having the same issue with only two accounts.

**Comment by Rysteranch** [comment]
It did start working.  I'm not sure what i did.  It started working after the update yesterday. I also tried launching without rr enabled,  so maybe that did it.

**Comment by mooreatv** [comment]
k thanks, will close this. also note there was an issue with latest windows update (24h2) which I just fixed
