### ISSUE TITLE
OMB  litle need update pls

### ISSUE THREAD

**Issue by tiqwicka** [WowOpenBox/WowOpenBox#161]
(1) for example OMB1 thanks to auto capture wow.exe is attached to OMB1 and the second wow to OMB2, but when wow (OMB1) throws me an error due to frequent account switching, the game crashes and is no longer launched and OMB does not register that the game is no longer active in OMB1 and I always have to right-click on OMB1, give forget OMB 1 and then update and or 2 keyboard shortcuts that I bid thanks to autohotkey to reset all windows and then give an update to assign new ones :D
 ___
(2) then OMB, the main OMB menu could have some kind of stay on TOP because as the other windows are in stay on top, the menu cannot be displayed through them and I have to use the powertoys always top script to display it at all

___
(3)
then deleting OMB windows selected, even if in the window layout I set auto to 2 OMB windows because I am shown 3 in the menu I save and I still have 3 windows there, it is a problem because I switch windows and when resetting all windows it starts when the game crashes in OMB2 to assign the newly launched to OMB3

**Comment by mooreatv** [comment]
for 1) you can use the ctrl-alt-shift-r (reset windows) to force wob to find out your window is missing/crashed, though it should also figure it out when you RR into it - also maybe more importantly your game isn't supposed to crash at all/ever

2) you can alt tab with your mouse on the right spot and the window should stay up, unless you used stay on top on other windows in which case it's better to have some hole somewhere

I don't understand 3) but maybe you want to create profiles if you want to switch dynamically between different number of windows, that works (it won't move/change the windows that are past the maximum set in a profile)
