### ISSUE TITLE
Existing WOB 1 when it isnt

### ISSUE THREAD

**Issue by Walhaelll** [WowOpenBox/WowOpenBox#162]
When I configure the program for the first time, everything is correct and it takes all the wow instances I have. However, when I open it again (having closed all the wow processes) I get the error that a WOB1 already exists and it never picks up the screen correctly.
**To Reproduce**

1. Start WOB
2. Start X Wow windows
3. Close all windows of WOW
4. Extract again the clean install of WOB
5. Open WOB

**Expected behavior**
Open WOB correctly.

**Screenshots**
![image](https://github.com/user-attachments/assets/c09e2585-54b5-4f33-9631-4af583eba146)

**Game:**
Vanilla wow

**Settings:**
Doesnt Exist

It fixes when i restart PC

**Comment by mooreatv** [comment]
you probably did have a WOB1 somewhere - closing this unless you can reproduce it
