### ISSUE TITLE
Possibility to delete hoykeys

### ISSUE THREAD

**Issue by ClowreedII** [WowOpenBox/WowOpenBox#164]
Petition to please add a way to delete hotkeys, since most of them interfere with eg. explorers like Opera or Chrome
When I delete a hotkey from the settings file it gets re-assinged automatically and I can't change it 
I tried assigning other crazy hotkeys but a lot of them are already taken it seems, and I don't even know which program is taking those

**Comment by mooreatv** [comment]
as mentioned in the faq to remove a hotkey edit the settings and set to ""
