### ISSUE TITLE
custom next/previous window rotations

### ISSUE THREAD

**Issue by mooreatv** [WowOpenBox/WowOpenBox#21]
allow keys with different rotation of windows

e.g.  2,3,4,5->2,3,4,5 etc skipping window 1

or 3,4,5,3,4,5 (dpses... but not tank or heals)

etc

**Comment by MikeLorenz** [comment]
To this, I would add a suggestion to have some keys swap to the prev/next window before and/or after sending the key code. For instance, to be able to set up a key to swap to the next window, then the key code and swap back.

**Comment by mooreatv** [comment]
this is done in 4.x
