### ISSUE TITLE
Next/new feature: (hot) keybind for window focus

### ISSUE THREAD

**Issue by mooreatv** [WowOpenBox/WowOpenBox#3]
vote to prioritize

**Comment by nodozen** [comment]
Gave this a thumbs up.  Not sure how to vote otherwise.

**Comment by nodozen** [comment]
Maybe break this into 2 separate enhancements or if you keep it one maybe make it:
#3A for Focus without Swap (keeping window size and location); and 
#3B) for focus with window swapping (make window move to primary/large window and put in focus;):  

For me the software isn't really that usable/helpful without at least #3A.

**Comment by mooreatv** [comment]
did #9 so I can save what is setup

**Comment by nodozen** [comment]
Thanks for the updates.  It it helps maybe put the hotkeys for window focus into a config file so that it can be user changeable.

**Comment by mooreatv** [comment]
fixed in https://github.com/WowOpenBox/WowOpenBox/commit/34c0549f2245a062747656537dad8637c23df6b4 !

**Comment by nodozen** [comment]
Working well.  Found that increasing the FPS of the background clients increases the speed of the focus change.  Recommend at least 30FPS for the background which does put higher loads on system.
