### ISSUE TITLE
a little love for EVE

### ISSUE THREAD

**Issue by poundjd** [WowOpenBox/WowOpenBox#77]
Please set up a page for EVE users with guides and other information.

**Comment by mooreatv** [comment]
I personally don't play eve, the extent of my testing was to launch and see it appeared it worked

Want to contribute an EVE online page in https://github.com/OpenMultiBoxing/WebSite
I would love to get sshots and info there

**Comment by mooreatv** [comment]
pole @poundjd

**Comment by poundjd** [comment]
I was not able to get it set up. if you could send me the instructions on
how to install it then I can help.
Mr. Jeffrey D. Pound, Sr.
To your own Morals be True.

**Comment by mooreatv** [comment]
https://github.com/WowOpenBox/WowOpenBox#installation

ie get the zip from the release page, extract both .exe to anywhere, double click?

pick "EVE online" in the game menu

what did you try and what doesn't work?

**Comment by mooreatv** [comment]
I am going to close this, do reopen if you tried and you encountered an issue
