### ISSUE TITLE
when restricting window layout to 1 screen only AND unchecking avoid taskbar area, windows are behind taskbar.

### ISSUE THREAD

**Issue by I3igAl** [WowOpenBox/WowOpenBox#93]
![screen layout issue](https://user-images.githubusercontent.com/80173503/110277067-6c59be80-7f89-11eb-9006-779b5d078b67.jpg)

when restricting the layout to only my first screen, but not avoiding the taskbar, the bottom edge ends up behind the taskbar obscuring part of the game window.

![screen layout issue 2](https://user-images.githubusercontent.com/80173503/110277401-0b7eb600-7f8a-11eb-8ddb-db61967ee9cc.jpg)
This problem does not happen when other screens are included in the layout. I have all wow clients set to windowed fullscreen before capture in both instances but it didnt seem to make a difference if they were regular windows first. I have tested this on WOB 3.7 and 3.8

**Comment by I3igAl** [comment]
Additional note with more testing: if the bottom windows are set Always on Top, they will go on top of the taskbar, but then nothing can be brought on top of the game client.

**Comment by mooreatv** [comment]
if you uncheck avoid taskbar that means you are ok with the windows and task bar fighting for the same space?

not sure what else would you expect to happen?

**Comment by I3igAl** [comment]
Check the task bar area in the two pictures. in the first one, when window layout is excluding screen 2 and 3 and only using 1, it fails to put the wow window on top of the taskbar. when the window layout spans multiple screens, it succeeds in putting on top of the taskbar. in both instances "avoid taskbar" is unchecked.

**Comment by mooreatv** [comment]
windows start on top of the task bar but as soon as the task bar has some change (like for when wow is blinking) it'll goes back on top (until you click back on the game to bring it to front (or RR to it) etc)

there is no difference in layout (or I am still missing your point, which is possible)

**Comment by mooreatv** [comment]
poke :) can I close this?

**Comment by I3igAl** [comment]
Minor issue solved by hiding taskbar if needed!
