### ISSUE TITLE
Request special field where I can put a key/keys that will force snapback of main window

### ISSUE THREAD

**Issue by Furyswipesvg** [WowOpenBox/WowOpenBox#96]
So, for example, say I put tab in that field. 
Every time I use tab, the original main(large) window toon will return to place as the large window and focus will be set there.

**Comment by I3igAl** [comment]
![image](https://user-images.githubusercontent.com/80173503/110604405-e8483800-813c-11eb-81b3-44c3f7a7de6e.png)
focusMain does what you are asking, default kebyind is control shift W i believe but you can manually change it. however more UI and less notepad editing will be nice.

**Comment by mooreatv** [comment]
you can do that with the 2nd rotation; and then there is #128 for even more rotations - so closing this one

**Comment by mooreatv** [comment]
Snap back exists on key down in 4.6.1 now
